name: build

on:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.mc }}
    runs-on: ubuntu-24.04
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        mc:
          - "1.20.1"
          - "1.20.2"
          - "1.20.3"
          - "1.20.4"
          - "1.20.5"
          - "1.20.6"
          - "1.21"
          - "1.21.1"
          - "1.21.2"
          - "1.21.3"
          - "1.21.4"
          - "1.21.5"
          - "1.21.6"
          - "1.21.7"
          - "1.21.8"
          - "1.21.9"
          - "1.21.10"
          - "1.21.11"
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v4
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build Minecraft ${{ matrix.mc }}
        env:
          SC_VERSION: ${{ matrix.mc }}
          GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.vfs.watch=false
        run: ./gradlew :${{ matrix.mc }}:build --stacktrace --no-daemon
      - name: capture build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: eternal-firework-rocket-${{ matrix.mc }}
          path: versions/${{ matrix.mc }}/build/libs/
          if-no-files-found: error
